import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Copy, Check, Share2, FileText, Download, BookOpen, ExternalLink } from 'lucide-react';
import { ChatSession, UserProfile } from '../../types';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  session: ChatSession | null;
  user: UserProfile;
}

export const ShareModal: React.FC<ShareModalProps> = ({
  isOpen,
  onClose,
  session,
  user,
}) => {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedTranscript, setCopiedTranscript] = useState(false);
  const [downloadedFormat, setDownloadedFormat] = useState<'md' | 'txt' | null>(null);

  if (!isOpen || !session) return null;

  const shareUrl = typeof window !== 'undefined'
    ? `${window.location.origin}${window.location.pathname}?session=${encodeURIComponent(session.id)}`
    : '';

  const handleCopyLink = async () => {
    try {
      if (navigator.clipboard && shareUrl) {
        await navigator.clipboard.writeText(shareUrl);
      } else {
        const textarea = document.createElement('textarea');
        textarea.value = shareUrl;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
      }
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2200);
    } catch (e) {
      console.error('Failed to copy link', e);
    }
  };

  const getMarkdownTranscript = () => {
    const header = `# Socratic Inquiry: ${session.title}\n**Learner**: ${user.name} | **Subject**: ${session.subject || 'General'} | **Date**: ${new Date(session.updatedAt).toLocaleDateString()}\n\n---\n\n`;
    const body = session.messages
      .map((m) => {
        const roleName = m.role === 'assistant' ? '🤖 Socratic Mentor (Socratic Guide)' : `👤 ${user.name}`;
        const time = new Date(m.timestamp).toLocaleTimeString();
        return `### ${roleName} _(${time})_\n\n${m.content}\n`;
      })
      .join('\n---\n\n');
    const footer = `\n\n---\n*Generated by [Socratic Mentor](https://ai.studio) — Socratic Learning Partner*`;
    return header + body + footer;
  };

  const handleCopyTranscript = async () => {
    try {
      const transcript = getMarkdownTranscript();
      if (navigator.clipboard) {
        await navigator.clipboard.writeText(transcript);
      }
      setCopiedTranscript(true);
      setTimeout(() => setCopiedTranscript(false), 2200);
    } catch (e) {
      console.error('Failed to copy transcript', e);
    }
  };

  const handleNativeShare = async () => {
    const shareData = {
      title: `Socratic Mentor: ${session.title}`,
      text: `Exploring "${session.title}" through Socratic inquiry on Socratic Mentor!`,
      url: shareUrl,
    };
    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        handleCopyLink();
      }
    } else {
      handleCopyLink();
    }
  };

  const handleDownload = (format: 'md' | 'txt') => {
    const content = getMarkdownTranscript();
    const mimeType = format === 'md' ? 'text/markdown;charset=utf-8' : 'text/plain;charset=utf-8';
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${session.title.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'dialogue'}.${format}`;
    a.click();
    URL.revokeObjectURL(url);

    setDownloadedFormat(format);
    setTimeout(() => setDownloadedFormat(null), 2200);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="fixed inset-0 bg-black/60 dark:bg-black/80 backdrop-blur-xs"
        />

        <motion.div
          initial={{ opacity: 0, scale: 0.96, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.96, y: 10 }}
          className="relative w-full max-w-lg max-h-[92dvh] overflow-y-auto bg-white dark:bg-[#161B22] border border-[#CBD5E1] dark:border-[#30363D] rounded-2xl p-6 shadow-2xl z-10 text-[#0F172A] dark:text-[#F0F6FC]"
        >
          <button
            onClick={onClose}
            className="absolute top-4 right-4 min-w-[36px] min-h-[36px] flex items-center justify-center text-[#64748B] dark:text-[#8B949E] hover:text-[#0F172A] dark:hover:text-[#F0F6FC] hover:bg-[#F1F5F9] dark:hover:bg-[#21262D] rounded-xl transition-colors cursor-pointer"
            aria-label="Close modal"
          >
            <X className="w-4 h-4" />
          </button>

          <div className="flex items-center gap-3 mb-5">
            <div className="w-10 h-10 rounded-xl bg-[#059669]/10 dark:bg-[#34D399]/15 border border-[#059669]/30 dark:border-[#34D399]/30 flex items-center justify-center text-[#059669] dark:text-[#34D399] shrink-0">
              <Share2 className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-[#0F172A] dark:text-[#F0F6FC]">
                Share Socratic Dialogue
              </h3>
              <p className="text-xs text-[#64748B] dark:text-[#8B949E]">
                Share your learning journey or export the dialogue notes
              </p>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-[#F8FAFC] dark:bg-[#0D1117] border border-[#E2E8F0] dark:border-[#30363D] mb-5 space-y-2">
            <div className="flex items-center justify-between gap-2">
              <span className="font-semibold text-sm text-[#0F172A] dark:text-[#F0F6FC] line-clamp-1">
                {session.title}
              </span>
              {session.subject && (
                <Badge variant="category" className="text-[10px] shrink-0">
                  {session.subject}
                </Badge>
              )}
            </div>
            <div className="flex items-center gap-4 text-xs text-[#64748B] dark:text-[#8B949E]">
              <span>{session.messages.length} exchanges</span>
              <span>•</span>
              <span>{session.conceptsMastered?.length || 0} mastered concepts</span>
              <span>•</span>
              <span>Updated {new Date(session.updatedAt).toLocaleDateString()}</span>
            </div>
          </div>

          <div className="space-y-2 mb-5">
            <label className="block text-xs font-semibold text-[#64748B] dark:text-[#8B949E]">
              Shareable Link
            </label>
            <div className="flex items-center gap-2">
              <input
                type="text"
                readOnly
                value={shareUrl}
                className="flex-1 px-3 py-2 text-xs bg-[#F1F5F9] dark:bg-[#0D1117] border border-[#CBD5E1] dark:border-[#30363D] rounded-xl text-[#0F172A] dark:text-[#F0F6FC] truncate focus:outline-none select-all"
              />
              <Button
                size="sm"
                onClick={handleCopyLink}
                className="shrink-0 gap-1.5 cursor-pointer"
              >
                {copiedLink ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-[#16A34A] dark:text-[#3FB950]" />
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Link</span>
                  </>
                )}
              </Button>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-5">
            <button
              onClick={handleCopyTranscript}
              className="flex items-center gap-3 p-3 rounded-xl border border-[#CBD5E1] dark:border-[#30363D] bg-white dark:bg-[#0D1117] hover:bg-[#F8FAFC] dark:hover:bg-[#21262D] text-left transition-all cursor-pointer shadow-2xs group"
            >
              <div className="w-8 h-8 rounded-lg bg-[#059669]/10 dark:bg-[#34D399]/15 flex items-center justify-center text-[#059669] dark:text-[#34D399] shrink-0">
                {copiedTranscript ? <Check className="w-4 h-4 text-[#16A34A] dark:text-[#3FB950]" /> : <FileText className="w-4 h-4" />}
              </div>
              <div className="min-w-0">
                <div className="text-xs font-semibold text-[#0F172A] dark:text-[#F0F6FC]">
                  {copiedTranscript ? 'Markdown Copied!' : 'Copy Markdown'}
                </div>
                <div className="text-[10px] text-[#64748B] dark:text-[#8B949E]">
                  Ready for Notion or Obsidian
                </div>
              </div>
            </button>

            <button
              onClick={handleNativeShare}
              className="flex items-center gap-3 p-3 rounded-xl border border-[#CBD5E1] dark:border-[#30363D] bg-white dark:bg-[#0D1117] hover:bg-[#F8FAFC] dark:hover:bg-[#21262D] text-left transition-all cursor-pointer shadow-2xs group"
            >
              <div className="w-8 h-8 rounded-lg bg-[#7C3AED]/10 dark:bg-[#BC8CFF]/15 flex items-center justify-center text-[#7C3AED] dark:text-[#BC8CFF] shrink-0">
                <ExternalLink className="w-4 h-4" />
              </div>
              <div className="min-w-0">
                <div className="text-xs font-semibold text-[#0F172A] dark:text-[#F0F6FC]">
                  Share via Apps
                </div>
                <div className="text-[10px] text-[#64748B] dark:text-[#8B949E]">
                  Send to social or chat apps
                </div>
              </div>
            </button>
          </div>

          <div className="pt-3 border-t border-[#E2E8F0] dark:border-[#30363D]">
            <div className="text-xs font-semibold text-[#64748B] dark:text-[#8B949E] mb-2 flex items-center gap-1.5">
              <Download className="w-3.5 h-3.5" />
              <span>Download Transcript</span>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => handleDownload('md')}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 px-3 rounded-xl border border-[#CBD5E1] dark:border-[#30363D] bg-[#F8FAFC] dark:bg-[#0D1117] hover:bg-[#F1F5F9] dark:hover:bg-[#21262D] text-xs font-medium text-[#0F172A] dark:text-[#F0F6FC] transition-colors cursor-pointer"
              >
                {downloadedFormat === 'md' ? <Check className="w-3.5 h-3.5 text-[#16A34A] dark:text-[#3FB950]" /> : <BookOpen className="w-3.5 h-3.5" />}
                <span>Markdown (.md)</span>
              </button>

              <button
                onClick={() => handleDownload('txt')}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 px-3 rounded-xl border border-[#CBD5E1] dark:border-[#30363D] bg-[#F8FAFC] dark:bg-[#0D1117] hover:bg-[#F1F5F9] dark:hover:bg-[#21262D] text-xs font-medium text-[#0F172A] dark:text-[#F0F6FC] transition-colors cursor-pointer"
              >
                {downloadedFormat === 'txt' ? <Check className="w-3.5 h-3.5 text-[#16A34A] dark:text-[#3FB950]" /> : <FileText className="w-3.5 h-3.5" />}
                <span>Plain Text (.txt)</span>
              </button>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
